# version format
version: "{build}"

# Operating system (build VM template)
os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\mh-cbon\go-msi

# skip_non_tags: true

# environment variables
environment:
  GOPATH: c:\gopath
  GO15VENDOREXPERIMENT: 1

# scripts that run after cloning repository
install:
  - curl -fsSv -o C:\wix310-binaries.zip http://static.wixtoolset.org/releases/v3.10.3.3007/wix310-binaries.zip
  - dir C:\
  - 7z x C:\wix310-binaries.zip -y -r -oC:\wix310
  - set PATH=C:\wix310;%PATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - go get -u github.com/Masterminds/glide

# to run your custom scripts instead of automatic MSBuild
build_script:
  - glide install
  - go build -o go-msi.exe main.go
  - .\go-msi.exe make --msi go-msi-x86-%APPVEYOR_REPO_TAG_NAME%.msi --version %APPVEYOR_REPO_TAG_NAME% --arch x86
  - .\go-msi.exe make --msi go-msi-x64-%APPVEYOR_REPO_TAG_NAME%.msi --version %APPVEYOR_REPO_TAG_NAME% --arch x64

# to disable automatic tests
test: off

# to disable deployment
deploy:
  - provider: GitHub
    artifact: /.*\.msi/           # upload all NuGet packages to release assets
    draft: false
    prerelease: false
    on:
      branch:
        - master
        - /v\d\.\d\.\d/
        - /\d\.\d\.\d/          # not so great solution found here http://help.appveyor.com/discussions/problems/3483-github-tag-push-doesnt-trigger-build
      appveyor_repo_tag: true       # deploy on tag push only
